" Get current vimrc path and directory
let s:rcpath=resolve(expand('<sfile>:p'))
let s:srcdir=fnamemodify(s:rcpath, ':h')

" Source external configs
execute 'source'.s:srcdir.'/plugins.vim'
execute 'source'.s:srcdir.'/mapping.vim'
execute 'source'.s:srcdir.'/settings.vim'

let plugins = glob(s:srcdir.'/plugged/*.vim',0 ,1)

" load all plugins
for file in plugins
    execute 'source' file
endfor

" Load local vimrc if it exists
if !empty(glob('~/.vimrc.local'))
    source ~/.vimrc.local
endif
